"""bandscribe.ingest.youtube and the URL path of bandscribe.ingest (M0_SPEC 12, 15).

Offline tests replace the yt-dlp call (youtube._run_ytdlp) with a fake that writes what yt-dlp would.
The one @network test downloads a short Creative Commons clip for real.
"""

from __future__ import annotations

import shutil
import socket
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

import pytest
import soundfile as sf

from fixtures import synth_audio
from bandscribe import atomic, paths, winjob
from bandscribe.config import Config
from bandscribe.ingest import IngestError, YoutubeError, content_key, ingest, youtube
from bandscribe.jobs.store import JobStore

VID = "YE7VzlLtp-4"  # Blender Foundation, "Big Buck Bunny" (CC BY 3.0)

# Network test clip: "Sintel" trailer (53 s) on the official Blender channel; Sintel is CC BY 3.0
# (Blender Foundation, durian.blender.org). Short on purpose: the Big Buck Bunny upload above is
# the whole 10-minute film, not a trailer.
NET_VID = "HOfdboHvshg"
NET_URL = f"https://www.youtube.com/watch?v={NET_VID}"


@pytest.fixture(autouse=True)
def _no_pacing(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "MIN_INTERVAL_S", 0.0)


@pytest.fixture(scope="module")
def webm(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """What YouTube format 251 looks like: Opus in WebM."""
    d = tmp_path_factory.mktemp("yt_audio")
    wav = d / "clip.wav"
    sf.write(str(wav), synth_audio.normal_mix(seconds=11.0).astype("float32"), synth_audio.SR, subtype="PCM_16")
    return synth_audio.ffmpeg_encode(wav, d / "clip.webm", synth_audio.CODECS["webm"])


def _info(vid: str = VID, **over: Any) -> dict[str, Any]:
    info: dict[str, Any] = {
        "id": vid,
        "title": "테스트 곡 (Official Audio)",
        "track": "테스트 곡",
        "artist": "Some Band",
        "artists": ["Some Band"],
        "album": "Album",
        "release_year": 2024,
        "uploader": "Some Band - Topic",
        "channel": "Some Band - Topic",
        "duration": 11,
        "chapters": [{"start_time": 0.0, "end_time": 11.0, "title": "Intro"}],
        "live_status": "not_live",
        "was_live": False,
        "format_id": "251",
        "acodec": "opus",
        "abr": 135.4,
        "asr": 48000,
        "ext": "webm",
        "description": "Provided to YouTube by Label\n\n" + "x" * 500 + "\n\nAuto-generated by YouTube.",
        "webpage_url": f"https://www.youtube.com/watch?v={vid}",
        "formats": [{"format_id": str(i)} for i in range(50)],  # bulk that must not reach meta.json
        "_version": {"version": "2026.09.27.232945"},
    }
    info.update(over)
    return info


class FakeYtdlp:
    """Stands in for youtube._run_ytdlp: records commands and writes <id>.<ext> + <id>.info.json."""

    def __init__(self, audio: Path | None, info: dict[str, Any] | None = None, rc: int = 0, stderr: str = "") -> None:
        self.audio, self.info, self.rc, self.stderr = audio, info or _info(), rc, stderr
        self.calls: list[list[str]] = []

    def __call__(self, cmd: list[str], timeout_s: float) -> subprocess.CompletedProcess[str]:
        self.calls.append(list(cmd))
        if self.rc == 0 and self.audio is not None:
            out_dir = Path(cmd[cmd.index("-o") + 1]).parent
            vid, ext = self.info["id"], self.info["ext"]
            shutil.copyfile(self.audio, out_dir / f"{vid}.{ext}")
            atomic.write_json(out_dir / f"{vid}.info.json", self.info)
        return subprocess.CompletedProcess(cmd, self.rc, stdout="", stderr=self.stderr)


def _forbid_network(cmd: list[str], timeout_s: float) -> subprocess.CompletedProcess[str]:
    raise AssertionError(f"yt-dlp must not run here: {cmd}")


@pytest.fixture
def ytenv(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Downloads under tmp and a dummy yt-dlp.exe, so offline tests never depend on tools/."""
    monkeypatch.setattr(paths, "DOWNLOADS", tmp_path / "downloads")
    exe = tmp_path / "tools" / "yt-dlp.exe"
    exe.parent.mkdir()
    exe.write_bytes(b"")
    monkeypatch.setattr(paths, "YTDLP_EXE", exe)
    return tmp_path


# ------------------------------------------------------------------------------------ video ids


@pytest.mark.parametrize(
    "url",
    [
        f"https://www.youtube.com/watch?v={VID}",
        f"http://youtube.com/watch?v={VID}&t=42s",
        f"https://www.youtube.com/watch?feature=share&v={VID}&list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf&index=3",
        f"https://m.youtube.com/watch?v={VID}",
        f"https://music.youtube.com/watch?v={VID}&si=AbCdEfGh",
        f"https://youtu.be/{VID}",
        f"https://youtu.be/{VID}?si=xyz123&t=10",
        f"https://www.youtube.com/shorts/{VID}?feature=share",
        f"https://www.youtube.com/embed/{VID}?start=5",
        f"https://www.youtube-nocookie.com/embed/{VID}",
        f"https://www.youtube.com/live/{VID}?si=1",
        f"youtu.be/{VID}",
        f"www.youtube.com/watch?v={VID}",
        f"HTTPS://WWW.YOUTUBE.COM/watch?v={VID}",
        f"  https://youtu.be/{VID}  ",
    ],
)
def test_parse_video_id_accepts(url: str) -> None:
    assert youtube.parse_video_id(url) == VID


@pytest.mark.parametrize(
    "url",
    [
        "",
        "not a url",
        r"C:\music\song.flac",
        "https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf",
        "https://www.youtube.com/@BlenderOfficial",
        "https://www.youtube.com/watch",
        "https://www.youtube.com/watch?v=short",
        f"https://www.youtube.com/watch?v={VID}X",
        f"https://example.com/watch?v={VID}",
        f"https://youtube.com.evil.example/watch?v={VID}",
        f"https://notyoutube.com/watch?v={VID}",
        "https://youtu.be/",
    ],
)
def test_parse_video_id_rejects(url: str) -> None:
    assert youtube.parse_video_id(url) is None


def test_canonical_url_drops_tracking() -> None:
    assert youtube.canonical_url(VID) == f"https://www.youtube.com/watch?v={VID}"


# -------------------------------------------------------------------------------- command / info


def test_build_command_follows_spec_and_never_uses_cookies(tmp_path: Path) -> None:
    cfg = Config()
    cmd = youtube.build_command(f"https://youtu.be/{VID}", tmp_path / "dl", cfg)
    assert cmd[0] == str(paths.YTDLP_EXE)
    assert cmd[cmd.index("--config-locations") + 1] == str(paths.YTDLP_CONF)
    assert "--ignore-config" in cmd  # no stray user/system yt-dlp config (could add cookies)
    assert cmd[cmd.index("--encoding") + 1] == "utf-8"  # the frozen exe would print cp949 otherwise
    assert "--no-playlist" in cmd and "--write-info-json" in cmd
    assert "--no-write-comments" in cmd and "--no-progress" in cmd
    assert cmd[cmd.index("-f") + 1] == cfg.youtube.format
    assert "drc" in cfg.youtube.format and "acodec=opus" in cfg.youtube.format
    assert cmd[cmd.index("-o") + 1] == str(tmp_path / "dl" / "%(id)s.%(ext)s")
    assert cmd[-1] == f"https://youtu.be/{VID}"
    assert "--no-cookies" in cmd and "--no-cookies-from-browser" in cmd
    assert not {"--cookies", "--cookies-from-browser"} & set(cmd)
    # no re-encoding / post-processing
    assert not {"-x", "--extract-audio", "--audio-format", "--recode-video", "--remux-video"} & set(cmd)


def test_build_command_refuses_cookies_even_with_consent(tmp_path: Path) -> None:
    cfg = Config.model_validate({"youtube": {"cookies": True}, "consent": {"cookies": "2026-10-01 test"}})
    with pytest.raises(YoutubeError, match="쿠키"):
        youtube.build_command(f"https://youtu.be/{VID}", tmp_path, cfg)


def test_trim_info_keeps_the_useful_part() -> None:
    t = youtube.trim_info(_info())
    expected = {"id", "title", "track", "artist", "artists", "album", "release_year", "uploader", "channel"}
    expected |= {"duration", "chapters", "live_status", "was_live", "format_id", "acodec", "abr", "asr", "ext"}
    assert expected <= set(t)
    assert t["format_id"] == "251" and t["abr"] == 135.4
    assert len(t["description_tail"]) == youtube.DESCRIPTION_TAIL_CHARS
    assert t["description_tail"].endswith("Auto-generated by YouTube.")
    assert t["is_art_track"] is True
    assert t["yt_dlp_version"] == "2026.09.27.232945"
    assert "formats" not in t and "description" not in t
    assert youtube.trim_info(_info(description="my band live"))["is_art_track"] is False
    assert youtube.trim_info(_info(description=None))["description_tail"] == ""


# ---------------------------------------------------------------------------------------- download


def test_download_with_fake_ytdlp(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    fake = FakeYtdlp(webm)
    monkeypatch.setattr(youtube, "_run_ytdlp", fake)
    out_dir = paths.DOWNLOADS / VID
    audio, info = youtube.download(f"https://youtu.be/{VID}", out_dir, Config())
    assert audio == out_dir / f"{VID}.webm" and audio.read_bytes() == webm.read_bytes()
    assert info["format_id"] == "251" and info["id"] == VID
    assert len(fake.calls) == 1 and "--no-cookies" in fake.calls[0]


def test_download_reuses_a_finished_download_offline(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    out_dir = paths.DOWNLOADS / VID
    out_dir.mkdir(parents=True)
    shutil.copyfile(webm, out_dir / f"{VID}.webm")
    atomic.write_json(out_dir / f"{VID}.info.json", _info())
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    audio, info = youtube.download(f"https://youtu.be/{VID}", out_dir, Config())
    assert audio.name == f"{VID}.webm" and info["id"] == VID


def test_download_ignores_a_partial_download(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    out_dir = paths.DOWNLOADS / VID
    out_dir.mkdir(parents=True)
    (out_dir / f"{VID}.webm.part").write_bytes(b"\x1a\x45partial")
    atomic.write_json(out_dir / f"{VID}.info.json", _info())
    fake = FakeYtdlp(webm)
    monkeypatch.setattr(youtube, "_run_ytdlp", fake)
    audio, _ = youtube.download(f"https://youtu.be/{VID}", out_dir, Config())
    assert len(fake.calls) == 1 and audio.suffix == ".webm"


def test_download_failure_has_stderr_tail_and_hint(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    err = "ERROR: [youtube] YE7VzlLtp-4: Sign in to confirm you're not a bot. 로그인 필요"
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(None, rc=1, stderr="WARNING: x\n" + err))
    with pytest.raises(YoutubeError) as ei:
        youtube.download(f"https://youtu.be/{VID}", paths.DOWNLOADS / VID, Config())
    msg = str(ei.value)
    assert err in msg and err in ei.value.stderr_tail
    assert "--update-to nightly" in msg and "로컬 파일" in msg
    assert isinstance(ei.value, IngestError)


def test_download_success_without_file_is_an_error(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(None, rc=0))
    with pytest.raises(YoutubeError, match="찾지 못했습니다"):
        youtube.download(f"https://youtu.be/{VID}", paths.DOWNLOADS / VID, Config())


def test_download_without_ytdlp_exe(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(paths, "YTDLP_EXE", ytenv / "missing" / "yt-dlp.exe")
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    with pytest.raises(YoutubeError, match="로컬 파일"):
        youtube.download(f"https://youtu.be/{VID}", paths.DOWNLOADS / VID, Config())


# A stand-in with yt-dlp.exe's process shape: the venv python.exe is a launcher (like the PyInstaller
# bootloader) whose real interpreter starts a grandchild (like node) that inherits stdout/stderr.
_HANG_WITH_GRANDCHILD = (
    "import os, subprocess, sys, time\n"
    "g = subprocess.Popen([sys.executable, '-c', 'import time; time.sleep(600)'])\n"
    "open(sys.argv[1], 'w', encoding='utf-8').write(f'{os.getpid()} {g.pid}')\n"
    "print('[download] stalled', file=sys.stderr, flush=True)\n"
    "time.sleep(600)\n"
)


@pytest.mark.skipif(not paths.CORE_PYTHON.is_file(), reason="core venv python needed as a launcher stand-in")
def test_run_ytdlp_timeout_kills_the_whole_tree(tmp_path: Path) -> None:
    """Regression: subprocess.run(timeout=) killed only the launcher and then waited for the orphan."""
    pid_file = tmp_path / "pids.txt"
    t0 = time.monotonic()
    with pytest.raises(YoutubeError, match="초 안에 끝나지 않아 중단했습니다") as ei:
        youtube._run_ytdlp([str(paths.CORE_PYTHON), "-c", _HANG_WITH_GRANDCHILD, str(pid_file)], 3)
    elapsed = time.monotonic() - t0
    assert elapsed < 3 + 8, f"returned after {elapsed:.1f} s"
    assert "[download] stalled" in ei.value.stderr_tail
    for pid in (int(p) for p in pid_file.read_text(encoding="utf-8").split()):
        deadline = time.monotonic() + 5
        while winjob.pid_alive(pid):
            assert time.monotonic() < deadline, f"pid {pid} survived the timeout"
            time.sleep(0.05)


def _ytdlp_pids() -> set[int]:
    out = subprocess.run(["tasklist", "/FI", "IMAGENAME eq yt-dlp.exe", "/FO", "CSV", "/NH"],
                         capture_output=True, text=True, encoding="utf-8", errors="replace").stdout
    return {int(row.split('","')[1]) for row in out.splitlines() if row.startswith('"yt-dlp')}


class _LocalServer:
    """127.0.0.1 only, so the real-exe tests below never touch the internet."""

    def __init__(self, handler: Any) -> None:
        self.sock = socket.socket()
        self.sock.bind(("127.0.0.1", 0))
        self.sock.listen(8)
        self.port = self.sock.getsockname()[1]
        self.held: list[socket.socket] = []
        threading.Thread(target=self._serve, args=(handler,), daemon=True).start()

    def _serve(self, handler: Any) -> None:
        while True:
            try:
                conn, _ = self.sock.accept()
            except OSError:
                return
            self.held.append(conn)
            handler(conn)

    def close(self) -> None:
        self.sock.close()
        for c in self.held:
            c.close()


@pytest.mark.slow
@pytest.mark.skipif(not paths.YTDLP_EXE.is_file(), reason="tools/yt-dlp.exe not installed")
def test_real_ytdlp_on_a_hanging_server_is_stopped_at_the_timeout(tmp_path: Path) -> None:
    server = _LocalServer(lambda conn: None)  # accepts, never answers
    before = _ytdlp_pids()
    try:
        cmd = [str(paths.YTDLP_EXE), "--ignore-config", "--encoding", "utf-8", "--socket-timeout", "60",
               "--no-progress", "-o", str(tmp_path / "%(id)s.%(ext)s"), f"http://127.0.0.1:{server.port}/a.mp3"]
        t0 = time.monotonic()
        with pytest.raises(YoutubeError, match="중단했습니다"):
            youtube._run_ytdlp(cmd, 6)
        elapsed = time.monotonic() - t0
    finally:
        server.close()
    assert elapsed < 6 + 10, f"returned after {elapsed:.1f} s (yt-dlp's own socket timeout is 60 s)"
    assert _ytdlp_pids() <= before, "a yt-dlp.exe process outlived the timeout"


@pytest.mark.slow
@pytest.mark.skipif(not paths.YTDLP_EXE.is_file(), reason="tools/yt-dlp.exe not installed")
def test_real_ytdlp_error_text_is_utf8(tmp_path: Path) -> None:
    """The frozen exe ignores PYTHONUTF8 and writes cp949 unless told --encoding utf-8."""

    def not_found(conn: socket.socket) -> None:
        try:
            conn.recv(65536)
            conn.sendall(b"HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\nConnection: close\r\n\r\n")
        except OSError:
            pass
        conn.close()

    server = _LocalServer(not_found)
    try:
        url = f"http://127.0.0.1:{server.port}/합주녹음.mp3"
        proc = youtube._run_ytdlp(youtube.build_command(url, tmp_path, Config()), 60)
    finally:
        server.close()
    assert proc.returncode != 0
    assert "�" not in proc.stderr, proc.stderr
    assert "합주녹음" in proc.stderr


# ------------------------------------------------------------------------------------------ pacing


def test_pace_spans_processes_via_the_stamp_file(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A second `bandscribe ingest <url>` is a new process: the wait must come from disk, not memory."""
    monkeypatch.setattr(youtube, "MIN_INTERVAL_S", 5.0)
    monkeypatch.setattr(youtube, "_last_download_end", 0.0)  # fresh process
    slept: list[float] = []
    monkeypatch.setattr(youtube.time, "sleep", slept.append)
    stamp = paths.DOWNLOADS / youtube.PACE_FILE
    atomic.write_text(stamp, f"{time.time() - 1.0:.3f}\n")
    youtube._pace()
    assert len(slept) == 1 and 3.5 < slept[0] <= 5.0
    # long ago, garbage, or a clock that went backwards: never more than MIN_INTERVAL_S, never an error
    for text in (f"{time.time() - 60:.3f}", "garbage", f"{time.time() + 3600:.3f}"):
        slept.clear()
        atomic.write_text(stamp, text)
        youtube._pace()
        assert all(0 < s <= 5.0 for s in slept)


def test_download_records_its_end_even_when_it_fails(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(None, rc=1, stderr="ERROR: nope"))
    t0 = time.time()
    with pytest.raises(YoutubeError):
        youtube.download(f"https://youtu.be/{VID}", paths.DOWNLOADS / VID, Config())
    stamp = float((paths.DOWNLOADS / youtube.PACE_FILE).read_text(encoding="utf-8"))
    assert t0 - 1 <= stamp <= time.time() + 1


# ------------------------------------------------------------------------------------- ingest(url)


def test_ingest_url_end_to_end_with_fake(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    fake = FakeYtdlp(webm)
    monkeypatch.setattr(youtube, "_run_ytdlp", fake)
    store = JobStore(ytenv / "jobs")
    r = ingest(f"https://music.youtube.com/watch?v={VID}&si=TRACKING", store=store, cfg=Config())
    assert r.cache_hit is False and r.song_key == f"yt-{VID}"
    meta = r.meta
    assert meta["source"]["kind"] == "youtube"
    assert meta["source"]["ref"] == f"https://www.youtube.com/watch?v={VID}"  # tracking parameter dropped
    assert meta["youtube"]["format_id"] == "251" and meta["youtube"]["abr"] == 135.4
    assert meta["youtube"]["title"] == "테스트 곡 (Official Audio)"
    assert meta["flags"]["drc"] is False
    inp = store.input_dir(r.song_key)
    assert meta["source"]["stored_as"] == "source.webm"
    assert (inp / "source.webm").read_bytes() == webm.read_bytes()  # original container, not re-encoded
    assert (inp / "mix_44k_f32.wav").is_file()
    assert store.index_get(f"yt:{VID}") == r.song_key
    assert store.index_get(f"file:{content_key(webm)}") == r.song_key
    assert (paths.DOWNLOADS / VID / f"{VID}.info.json").is_file()
    assert len(fake.calls) == 1

    # Second time: cache hit before any network access, whatever the URL shape.
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    shutil.rmtree(paths.DOWNLOADS)  # not even the download cache is needed
    for url in (f"https://youtu.be/{VID}?si=other", f"https://www.youtube.com/watch?v={VID}"):
        again = ingest(url, store=store, cfg=Config())
        assert again.cache_hit is True and again.song_key == r.song_key and again.meta == meta

    # The downloaded file given as a local file maps to the same job.
    local = ingest(str(inp / "source.webm"), store=store, cfg=Config())
    assert local.cache_hit is True and local.song_key == r.song_key


def test_ingest_url_heals_lost_index(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(webm))
    store = JobStore(ytenv / "jobs")
    ingest(f"https://youtu.be/{VID}", store=store, cfg=Config())
    store.index_path.unlink()
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    r = ingest(f"https://youtu.be/{VID}", store=store, cfg=Config())
    assert r.cache_hit is True and store.index_get(f"yt:{VID}") == r.song_key


def test_ingest_url_flags_drc_stream(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(webm, _info(format_id="251-drc")))
    r = ingest(f"https://youtu.be/{VID}", store=JobStore(ytenv / "jobs"), cfg=Config())
    assert r.meta["flags"]["drc"] is True


def test_ingest_url_is_on_by_default(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """User request 2026-09-30: a YouTube link works with the default config, no opt-in needed."""
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(webm))
    r = ingest(f"https://youtu.be/{VID}", store=JobStore(ytenv / "jobs"), cfg=Config())
    assert r.song_key == f"yt-{VID}"


def test_ingest_url_refused_when_disabled(ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    cfg = Config.model_validate({"youtube": {"enabled": False}})
    store = JobStore(ytenv / "jobs")
    with pytest.raises(IngestError, match="꺼져 있습니다"):
        ingest(f"https://youtu.be/{VID}", store=store, cfg=cfg)
    assert not paths.DOWNLOADS.exists()


@pytest.mark.parametrize("url", ["https://www.youtube.com/playlist?list=PL123", "https://example.com/song.mp3"])
def test_ingest_rejects_urls_without_a_video(url: str, ytenv: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    with pytest.raises(IngestError, match="YouTube 동영상 주소"):
        ingest(url, store=JobStore(ytenv / "jobs"), cfg=Config())


def test_ingest_url_detects_case_colliding_job(ytenv: Path, webm: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """NTFS is case-insensitive, video ids are not: yt-<id> and yt-<ID> share one folder."""
    monkeypatch.setattr(youtube, "_run_ytdlp", FakeYtdlp(webm))
    store = JobStore(ytenv / "jobs")
    ingest(f"https://youtu.be/{VID}", store=store, cfg=Config())
    other = VID.swapcase()
    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    with pytest.raises(IngestError, match="대소문자"):
        ingest(f"https://youtu.be/{other}", store=store, cfg=Config())


# ------------------------------------------------------------------------------------------ network


@pytest.mark.network
@pytest.mark.slow
def test_network_cc_clip_end_to_end(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    if not paths.YTDLP_EXE.is_file():
        pytest.skip(f"{paths.YTDLP_EXE} not installed")
    monkeypatch.setattr(paths, "DOWNLOADS", tmp_path / "downloads")
    calls: list[list[str]] = []
    real = youtube._run_ytdlp

    def spy(cmd: list[str], timeout_s: float) -> subprocess.CompletedProcess[str]:
        calls.append(list(cmd))
        return real(cmd, timeout_s)

    monkeypatch.setattr(youtube, "_run_ytdlp", spy)
    store = JobStore(tmp_path / "jobs")
    r = ingest(NET_URL, store=store, cfg=Config())

    assert r.cache_hit is False and r.song_key == f"yt-{NET_VID}"
    yt = r.meta["youtube"]
    assert yt["id"] == NET_VID and yt["channel"] == "Blender"
    assert yt["format_id"] and "drc" not in yt["format_id"]
    assert isinstance(yt["abr"], (int, float)) and yt["abr"] > 0
    assert yt["acodec"] and yt["ext"]
    assert 40 < r.meta["duration_s"] < 70
    # no cookies: the only yt-dlp call disabled them explicitly, and our config file adds none
    assert len(calls) == 1
    assert "--no-cookies" in calls[0] and "--no-cookies-from-browser" in calls[0]
    assert not {"--cookies", "--cookies-from-browser"} & set(calls[0])
    assert "cookies" not in paths.YTDLP_CONF.read_text(encoding="utf-8").lower()
    # original container kept byte for byte
    stored = store.input_dir(r.song_key) / r.meta["source"]["stored_as"]
    downloaded = paths.DOWNLOADS / NET_VID / f"{NET_VID}.{yt['ext']}"
    assert stored.read_bytes() == downloaded.read_bytes()
    assert r.meta["loudness"]["output_true_peak_dbfs"] <= Config().ingest.true_peak_ceiling_dbfs

    monkeypatch.setattr(youtube, "_run_ytdlp", _forbid_network)
    again = ingest(f"https://youtu.be/{NET_VID}?si=x", store=store, cfg=Config())
    assert again.cache_hit is True and again.song_key == r.song_key
