"""YouTube input via tools/yt-dlp.exe (DESIGN S0, M0_SPEC 12).

On by default since the user's 2026-09-30 request (risk notice acknowledged, recorded under [consent]
in data/config.toml). What stays off regardless: cookies and PO tokens (extra risk: account
suspension, further circumvention), playlists, re-encoding. The downloaded container is kept as is.
"""

from __future__ import annotations

import logging
import re
import subprocess
import threading
import time
import urllib.parse
from pathlib import Path
from typing import Any

from gtab import atomic, paths, winjob
from gtab.ingest.decode import IngestError, stderr_tail

log = logging.getLogger(__name__)

UPDATE_HINT = (
    "yt-dlp -U 또는 --update-to nightly, 실패하면 로컬 파일을 넣어 주세요. "
    r"(예: D:\gtab\tools\yt-dlp.exe --update-to nightly)"
)
# DESIGN S0: pause 5-10 s between downloads. Every `gtab ingest <url>` is its own process, so the end
# time of the last download is kept on disk (PACE_FILE under paths.DOWNLOADS). Tests set this to 0.
MIN_INTERVAL_S = 5.0
PACE_FILE = ".last_download"
DESCRIPTION_TAIL_CHARS = 200
ART_TRACK_MARKER = "Auto-generated by YouTube."

_ID_RE = re.compile(r"^[A-Za-z0-9_-]{11}$")
_PATH_ID_PREFIXES = ("shorts", "embed", "live", "v", "e")
_NOT_AUDIO_SUFFIXES = {".json", ".part", ".ytdl", ".temp", ".tmp", ".jpg", ".webp", ".png"}
_pace_lock = threading.Lock()
_last_download_end = 0.0  # time.time() of the last download that ended in this process


class YoutubeError(IngestError):
    """yt-dlp failed. ``stderr_tail`` holds the end of its stderr for the log."""

    def __init__(self, message: str, stderr_tail: str = "") -> None:
        super().__init__(message)
        self.stderr_tail = stderr_tail


def _is_youtube_host(host: str) -> bool:
    host = host.lower().rstrip(".")
    return (
        host in ("youtube.com", "youtu.be", "youtube-nocookie.com")
        or host.endswith(".youtube.com")
        or host.endswith(".youtube-nocookie.com")
    )


def parse_video_id(url: str) -> str | None:
    """Video id from the usual URL shapes, or None.

    Handles watch?v=, youtu.be/<id>, /shorts/<id>, /embed/<id>, /live/<id>, music.youtube.com and m.,
    any extra query parameters (list=, t=, si=, feature=) and a missing scheme.
    """
    s = (url or "").strip()
    if not s:
        return None
    if not re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*://", s):
        s = "https://" + s
    try:
        parts = urllib.parse.urlsplit(s)
        host = parts.hostname or ""
    except ValueError:
        return None
    if not _is_youtube_host(host):
        return None
    segments = [p for p in parts.path.split("/") if p]
    candidate: str | None = None
    if host.lower() == "youtu.be":
        candidate = segments[0] if segments else None
    elif segments and segments[0] == "watch":
        candidate = (urllib.parse.parse_qs(parts.query).get("v") or [None])[0]
    elif len(segments) >= 2 and segments[0] in _PATH_ID_PREFIXES:
        candidate = segments[1]
    if candidate and _ID_RE.match(candidate):
        return candidate
    return None


def canonical_url(video_id: str) -> str:
    """Stored instead of the user's URL: drops tracking parameters such as si=."""
    return f"https://www.youtube.com/watch?v={video_id}"


def build_command(url: str, out_dir: Path, cfg: Any) -> list[str]:
    ycfg = cfg.youtube
    if getattr(ycfg, "cookies", False) or getattr(ycfg, "po_token", False):
        # The config allows them only with a [consent] entry, but no M0 code path passes them to
        # yt-dlp; failing is better than silently downloading without what the user asked for.
        raise YoutubeError("youtube.cookies / youtube.po_token 은 아직 지원하지 않습니다(M0 는 쿠키·PO 토큰 없이만 받습니다).")
    return [
        str(paths.YTDLP_EXE),
        # Only our config file: a stray user/system yt-dlp config could add cookies or post-processing.
        "--ignore-config",
        # The frozen exe ignores PYTHONUTF8/PYTHONIOENCODING and would print in the console code page
        # (cp949 here); we decode its output as UTF-8, so Korean error text would turn into U+FFFD.
        "--encoding", "utf-8",
        "--config-locations", str(paths.YTDLP_CONF),
        "--no-playlist",
        "-f", str(ycfg.format),
        "--write-info-json",
        "--no-write-comments",
        "--no-progress",
        "--no-cookies",
        "--no-cookies-from-browser",
        "-o", str(Path(out_dir) / "%(id)s.%(ext)s"),
        url,
    ]


def trim_info(info: dict[str, Any]) -> dict[str, Any]:
    """The part of yt-dlp's info.json worth keeping in meta.json (the full file stays in downloads/)."""
    desc = info.get("description") or ""
    version = info.get("_version")
    return {
        "id": info.get("id"),
        "title": info.get("title"),
        "track": info.get("track"),
        "artist": info.get("artist"),
        "artists": info.get("artists"),
        "album": info.get("album"),
        "release_year": info.get("release_year"),
        "uploader": info.get("uploader"),
        "channel": info.get("channel"),
        "duration": info.get("duration"),
        "chapters": info.get("chapters"),
        "live_status": info.get("live_status"),
        "was_live": info.get("was_live"),
        "format_id": info.get("format_id"),
        "acodec": info.get("acodec"),
        "abr": info.get("abr"),
        "asr": info.get("asr"),
        "ext": info.get("ext"),
        "description_tail": desc[-DESCRIPTION_TAIL_CHARS:],
        "is_art_track": desc.rstrip().endswith(ART_TRACK_MARKER),
        "webpage_url": info.get("webpage_url"),
        "yt_dlp_version": version.get("version") if isinstance(version, dict) else None,
    }


def _find_download(out_dir: Path, video_id: str | None) -> tuple[Path, dict[str, Any]] | None:
    """(audio file, full info) of a finished download in ``out_dir``, or None.

    yt-dlp renames ``.part`` to the final name only when the download completed, so a final-named
    file next to its info.json means a whole file.
    """
    if video_id:
        info_path = out_dir / f"{video_id}.info.json"
        if not info_path.is_file():
            return None
    else:
        found = sorted(out_dir.glob("*.info.json"), key=lambda p: p.stat().st_mtime)
        if not found:
            return None
        info_path = found[-1]
    try:
        info = atomic.read_json(info_path)
    except (OSError, ValueError):
        return None
    vid = info.get("id") or video_id
    preferred = out_dir / f"{vid}.{info.get('ext')}"
    if preferred.is_file():
        return preferred, info
    others = [
        p for p in out_dir.glob(f"{vid}.*")
        if p.is_file() and p.suffix.lower() not in _NOT_AUDIO_SUFFIXES and not p.name.endswith(".info.json")
    ]
    if not others:
        return None
    return max(others, key=lambda p: p.stat().st_size), info


def _pace_file() -> Path:
    return Path(paths.DOWNLOADS) / PACE_FILE  # looked up at call time (tests repoint DOWNLOADS)


def _last_end() -> float:
    """Wall-clock end of the last download, by this or any earlier gtab process (0.0 if unknown)."""
    stamp = 0.0
    try:
        stamp = float(_pace_file().read_text(encoding="utf-8").strip() or 0.0)
    except (OSError, ValueError):
        pass
    with _pace_lock:
        return max(stamp, _last_download_end)


def _pace() -> None:
    # Clamped to MIN_INTERVAL_S so a stamp from a clock that later went backwards cannot stall us.
    wait = min(MIN_INTERVAL_S, _last_end() + MIN_INTERVAL_S - time.time())
    if wait > 0:
        log.info("waiting %.1f s between YouTube downloads", wait)
        time.sleep(wait)


def _mark_download_end() -> None:
    global _last_download_end
    now = time.time()
    with _pace_lock:
        _last_download_end = now
    try:
        atomic.write_text(_pace_file(), f"{now:.3f}\n")
    except OSError as e:  # pacing is politeness, never a reason to fail the ingest
        log.warning("could not record the download time in %s: %s", _pace_file(), e)


def _run_ytdlp(cmd: list[str], timeout_s: float) -> subprocess.CompletedProcess[str]:
    """Run yt-dlp with a real deadline.

    yt-dlp.exe is a PyInstaller one-file exe: a bootloader process starts the real yt-dlp as a child
    (which may start node for the JS challenge). winjob.run_captured keeps the whole tree in a
    kill-on-close Job Object, so a timeout, Ctrl+C or a crash of gtab ends every one of them and no
    orphan keeps writing into downloads/<id>/.
    """
    try:
        run = winjob.run_captured(cmd, timeout_s=timeout_s, env=paths.child_env())
    except OSError as e:
        raise YoutubeError(f"yt-dlp 실행 실패: {e}\n{UPDATE_HINT}") from e
    if run.timed_out:
        tail = stderr_tail(run.stderr)
        raise YoutubeError(
            f"yt-dlp 가 {timeout_s:.0f} 초 안에 끝나지 않아 중단했습니다 (youtube.timeout_s).\n{tail}\n{UPDATE_HINT}", tail
        )
    return subprocess.CompletedProcess(run.args, run.returncode if run.returncode is not None else -1, run.stdout, run.stderr)


def download(url: str, out_dir: Path, cfg: Any) -> tuple[Path, dict[str, Any]]:
    """Download the best audio-only stream of one video into ``out_dir``.

    Returns (audio path, trim_info(info)). A finished earlier download in ``out_dir`` is reused
    without touching the network (e.g. when decoding failed after a successful download).
    """
    out_dir = Path(out_dir)
    video_id = parse_video_id(url)
    existing = _find_download(out_dir, video_id) if out_dir.is_dir() else None
    if existing is not None:
        log.info("reusing earlier download %s", existing[0])
        return existing[0], trim_info(existing[1])

    if not paths.YTDLP_EXE.is_file():
        raise YoutubeError(f"yt-dlp.exe 가 없습니다: {paths.YTDLP_EXE}\n로컬 파일을 넣어 주세요.")
    cmd = build_command(url, out_dir, cfg)
    out_dir.mkdir(parents=True, exist_ok=True)
    _pace()
    log.info("yt-dlp: downloading %s", url)
    try:
        proc = _run_ytdlp(cmd, float(cfg.youtube.timeout_s))
    finally:
        _mark_download_end()  # failed attempts count too: they also hit YouTube
    if proc.returncode != 0:
        tail = stderr_tail(proc.stderr)
        raise YoutubeError(f"YouTube 다운로드에 실패했습니다 (yt-dlp 종료 코드 {proc.returncode}).\n{tail}\n{UPDATE_HINT}", tail)

    found = _find_download(out_dir, video_id)
    if found is None:
        tail = stderr_tail(proc.stderr)
        raise YoutubeError(f"yt-dlp 는 끝났지만 받은 오디오 파일을 찾지 못했습니다: {out_dir}\n{tail}\n{UPDATE_HINT}", tail)
    audio, info = found
    trimmed = trim_info(info)
    log.info("yt-dlp: %s format %s (%s, %s kbps)", audio.name, trimmed["format_id"], trimmed["acodec"], trimmed["abr"])
    return audio, trimmed
